name: Close sub-issues when PR merged

on:
  pull_request:
    types: [closed]

jobs:
  close-sub-issues:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            // Epic issue numarasını PR body’sinden çekiyoruz (ör: "Closes #100")
            const body = context.payload.pull_request.body;
            const epicMatch = body && body.match(/Closes #(\d+)/i);
            if (!epicMatch) {
              console.log("No epic issue referenced in PR body.");
              return;
            }
            const epicNumber = epicMatch[1];
            // Epic issue'yu al
            const epicIssue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(epicNumber),
            });
            const issueBody = epicIssue.data.body;
            const regex = /- \[.\] #(\d+)/g;
            let match;
            const subIssues = [];
            while ((match = regex.exec(issueBody)) !== null) {
              subIssues.push(match[1]);
            }
            for (const issueNumber of subIssues) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: Number(issueNumber),
                state: 'closed'
              });
            }
